Log file created at: 2017/05/05 21:40:16
Running on machine: DESKTOP-9JBUH7N
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0505 21:40:16.500128  6944 c_interface.cc:59] InvalidOperation :  Empty token at line 36608, file vocab.vk.txt
E0505 21:42:37.788513  6944 c_interface.cc:59] ArgumentOutOfRangeException :  CollectionParser.num_docs (D) == 0, out of range.
E0505 22:03:40.495612  6944 c_interface.cc:59] ArgumentOutOfRangeException :  CollectionParser.num_docs (D) == 0, out of range.
E0505 22:07:08.020295  6944 c_interface.cc:59] ArgumentOutOfRangeException :  CollectionParser.num_docs (D) == 0, out of range.
E0505 22:08:45.403018  6944 c_interface.cc:59] ArgumentOutOfRangeException :  CollectionParser.num_docs (D) == 0, out of range.
E0505 22:13:14.390075  6944 c_interface.cc:59] InvalidOperation :  Error at line2 or 4, file docword.vk.txt. Expected format: item_id token_id n_wd
E0505 22:35:01.943084  6944 c_interface.cc:324] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: class boost::exception_detail::clone_impl<struct boost::exception_detail::error_info_injector<class std::ios_base::failure> >
std::exception::what: failed opening file: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.
: iostream stream error
E0505 22:35:01.943084  6944 c_interface.cc:59] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: class boost::exception_detail::clone_impl<struct boost::exception_detail::error_info_injector<class std::ios_base::failure> >
std::exception::what: failed opening file: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.
: iostream stream error
E0505 22:35:21.633872  6944 c_interface.cc:324] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: class boost::exception_detail::clone_impl<struct boost::exception_detail::error_info_injector<class std::ios_base::failure> >
std::exception::what: failed opening file: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.
: iostream stream error
E0505 22:35:21.633872  6944 c_interface.cc:59] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: class boost::exception_detail::clone_impl<struct boost::exception_detail::error_info_injector<class std::ios_base::failure> >
std::exception::what: failed opening file: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.
: iostream stream error
W0505 22:43:16.567232  6944 collection_parser.cc:241] 37393 aren't present in parsed collection
W0505 22:59:07.604429  6944 collection_parser.cc:241] 37393 aren't present in parsed collection
W0505 23:11:11.128433  4896 perplexity.cc:125] Error in perplexity dictionary for token славица, class @default_class (and potentially for other tokens). Verify that the token exists in the dictionary and it's value > 0. Document unigram model will be used for this token (and for all other tokens under the same conditions).
E0505 23:11:11.623795 12044 c_interface.cc:59] InvalidOperation :  FitOffline: no tokens in effect --- either tokens not present in the model, or tokens were ignored due to class_id
E0505 23:15:30.161336 12428 c_interface.cc:59] InvalidOperation :  FitOffline: no tokens in effect --- either tokens not present in the model, or tokens were ignored due to class_id
E0505 23:18:27.313330  1756 c_interface.cc:59] InvalidOperation :  FitOffline: no tokens in effect --- either tokens not present in the model, or tokens were ignored due to class_id
E0505 23:18:50.388170 11728 c_interface.cc:59] InvalidOperation :  FitOffline: no tokens in effect --- either tokens not present in the model, or tokens were ignored due to class_id
